-- Avante configuration is handled in init.lua via lazy.nvim opts
-- This file is kept for reference but not loaded
--
-- Current config:
--   provider = "ollama"
--   model = "qwen3-coder:30b"
--   endpoint = "http://localhost:11434"
