require('web-icons')
require('lualine-config')
require('lsp-config')
require('colorscheme')
require('mkdnflow-config')
require('neotree')
require('bufferline-config')
-- require('neorg-config')
require('Comment').setup()
require('claude-code-config')
